# Generated by Django 3.1.7 on 2021-03-31 07:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'AdminPanel'), (2, 'ModuloGeral'), (3, 'ModuloCrianca'), (4, 'ModuloJuvel'), (5, 'ModuloMulher'), (6, 'Cultura'), (6, 'Patrimonio'), (7, 'Fiscalizacao')], default=1, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deficiencia', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casaNum', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estrutura', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabilitacaoLiteraria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habilitacaoLiteraria', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('dataAdmissaoIgreja', models.DateField()),
                ('batizado', models.CharField(max_length=50)),
                ('orfao', models.CharField(max_length=20)),
                ('parteOrfao', models.CharField(max_length=50)),
                ('numeroCartao', models.CharField(max_length=50)),
                ('estadoReligioso', models.CharField(max_length=50)),
                ('portadorDeficiencia', models.CharField(max_length=50)),
                ('selecionaAdeficiencia', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('imagem', models.FileField(upload_to='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.area')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicao', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profissao', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tribo', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubEstrutura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subestrutura', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estruturaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estrutura')),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=150)),
                ('numRua', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('bairroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissaoMembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DesignacaoColectiva', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estado')),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
                ('profissaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.profissao')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('provinciaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='MembrosSubEstrutura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('funcaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.funcao')),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
                ('posicaoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.posicao')),
                ('subEstruturaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.subestrutura')),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.municipio'),
        ),
        migrations.CreateModel(
            name='HabilitacaoLiterariaMembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.curso')),
                ('estadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estado')),
                ('habilitacaoLiterariaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.habilitacaoliteraria')),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomePai', models.CharField(max_length=150)),
                ('nomeMae', models.CharField(max_length=150)),
                ('PaiTocoista', models.CharField(max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
            ],
        ),
        migrations.CreateModel(
            name='EstruturaClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estruturaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estrutura')),
            ],
        ),
        migrations.CreateModel(
            name='estadoMembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoHabiliatacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.estado')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoMembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('enderecoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.endereco')),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
            ],
        ),
        migrations.AddField(
            model_name='endereco',
            name='RuaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.rua'),
        ),
        migrations.CreateModel(
            name='ContactoMembro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('contactoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.contacto')),
                ('membroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.membro')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='TipoContactoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.tipocontacto'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.municipio'),
        ),
        migrations.AddField(
            model_name='area',
            name='triboId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.tribo'),
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
