# Generated by Django 3.1.7 on 2021-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_classe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='condicaoIndividual',
            field=models.CharField(default='Não Aplicável', max_length=50),
        ),
    ]
