# Generated by Django 3.1.7 on 2021-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_classe', '0002_membro_condicaoindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='sustento',
            field=models.CharField(default='Pais', max_length=50),
        ),
    ]
