# Generated by Django 3.1.7 on 2021-04-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_classe', '0004_membro_dentrosistemaensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ruaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestao_classe.rua'),
        ),
    ]
