# Generated by Django 3.1.7 on 2021-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_classe', '0005_membro_ruaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='selecionaAdeficiencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
