# Generated by Django 3.1.7 on 2021-04-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestao_classe', '0006_auto_20210414_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='orfao',
            field=models.CharField(max_length=50),
        ),
    ]
